# Application configuration
spring.application.name=pmqsmonitor
server.port=8083

# Activate local profile for local properties
spring.profiles.active=local

# Default JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Logging
logging.level.com.example.pmqsmonitor=DEBUG
logging.level.org.springframework.web.reactive.function.client.WebClient=DEBUG

# TheyWorkForYou API
app.twfy.base-url=https://www.theyworkforyou.com/api/

