spring.profiles.active=local
server.port=8081

# Spring Data JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# File upload limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Disable OSIV (Open Session In View)
spring.jpa.open-in-view=false
